### ISSUE TITLE
Random order of resources

### ISSUE THREAD

**Issue by kevinrenskers** [raml-org/raml-js-parser#102]
I've split my (rather large) RAML file up into different files and my main file now looks like this:

```
#%RAML 0.8
title: Example
version: 1
baseUri: http://example.com/{version}

/account: !include account.raml
/status: !include status.raml
/channels: !include channels.raml
/conversations: !include conversations.raml
/organisations: !include organisations.raml
/users: !include users.raml
/groups: !include groups.raml
/feeds: !include feeds.raml
/switches: !include switches.raml
/locations: !include locations.raml
/shifts: !include shifts.raml
/tasks: !include tasks.raml
/upload: !include upload.raml
```

Now whenever I parse this via `loadFile` I get the resources in a random order. This is a problem in my raml2html renderer (see https://github.com/kevinrenskers/raml2html/issues/6) because the html output is now always different, causing much confusion.

**Comment by kevinrenskers** [comment]
@usarid Any news on this? It's now been almost 7 months since the last update.

**Comment by albertortizl** [comment]
Any news?

**Comment by kevinrenskers** [comment]
Anyone? @usarid?

**Comment by blakeembrey** [comment]
@kevinrenskers Could you try the latest release? It should have fixed the resolved order of files and attaching to properties by separating it into a two step process.

**Comment by kevinrenskers** [comment]
Works beautifully!

**Comment by albertortizl** [comment]
Hi guys!

Do you know when the new version will be available in your online framework?

https://anypoint.mulesoft.com/

**Comment by dmartinezg** [comment]
Hi @albertortizl, while we try to keep this repo clean of anything mentioning the Anypoint Platform I can answer, we are looking at a release of the latest version of #mulesoft/api-designer and #mulesoft/api-console (which will include this fix), some time next week.

**Comment by albertortizl** [comment]
Thanks!
