### ISSUE TITLE
FileReader::fetchFileAsync performance and indeterministic failures

### ISSUE THREAD

**Issue by Ezku** [raml-org/raml-js-parser#104]
Hi,

I recently had the pleasure of writing a library that creates accessible REST resource objects out of RAML descriptor files. For this I used raml-parser as a node module, and things worked out mostly fine. I had a bit of a tricky time getting everything set up though, for two reasons.

Reading a RAML file with multiple files as dependencies takes quite a lot of time comparatively, even on localhost. Like so:

    reading a raml schema file
      ✓ should accept a url and return a schema (460ms)

This is surprising, but not a dealbreaker, although it does slow down my test runs and thus requires special attention.

Once I did get the setup right, it would start halting async execution for no apparent reason, then maybe start working again at the next run. I couldn't find a pattern to things, and whether I cleaned up the repo's root from any number of temporary files between runs didn't seem to have any effect. I tracked things down to FileReader::fetchFileAsync, which would apparently not resolve.

I ran ramlParser.loadFile with a FileReader of my own passed to it, and managed to circumvent the problem. Not only does it work consistently, but it's much more performant.

    reading a raml schema file
      ✓ should accept a url and return a schema (56ms)

So, heads up: your XMLHttpRequest library of choice is likely broken for some use cases. For what it's worth, I'm running a static express server with node.js to serve static test data and used [superagent](https://github.com/visionmedia/superagent) for the replacement, but YMMV.

Again, thanks, I appreciate your work on RAML! _b

Cheers,
Eevert

**Comment by blakeembrey** [comment]
This shouldn't be an issue anymore. If this happens for anyone, feel free to comment or create a new issue for us to look at.
