### ISSUE TITLE
Unknown Protocol error on windows with 

### ISSUE THREAD

**Issue by eibrahim** [raml-org/raml-js-parser#110]
I get this error when I run osprey on a hello world project.  Same project works on mac but not on windows.

```
{ [Error: unknown protocol d:]
  context: 'while reading D:\\Dropbox\\projects\\demo\\api\\src\\assets\\raml\\api.raml',
  context_mark: null,
  message: 'unknown protocol d:',
  problem_mark: null,
  note: undefined }
```

PS: see more details at https://github.com/mulesoft/osprey/issues/61

**Comment by blakeembrey** [comment]
Fixed with https://github.com/raml-org/raml-js-parser/pull/122
