### ISSUE TITLE
Parser failing to load resource files when context is "/api"

### ISSUE THREAD

**Issue by marianomerlo** [raml-org/raml-js-parser#114]
I'm using OSPREY as follows:

var api = osprey.create('/api', app, {
  ramlFile: path.join(__dirname, '../raml_spec/api_spec.raml'),
  logLevel: app.get('env') !== 'test' ? 'debug' : 'off'
});

The API is loaded OK but when i want to open the console at /api/console it crashes because it can not load any resource file (json and schema) defined in the raml file.

The request to the file should be localhost:3000/api/fileName.json, but instead it's doing localhost:3000/fileName.json

If the context value is "/api/anything" then the console works ok.

**Comment by blakeembrey** [comment]
@marianomerlo I'm closing this since it's an issue with `osprey@0.1.x`, not the RAML parser.
