### ISSUE TITLE
Errors/exceptions in load handler are swallowed without trace

### ISSUE THREAD

**Issue by mgurov** [raml-org/raml-js-parser#123]
When using library from node.js, occasional errors/exceptions that are caused by my load hander are silently lost without trace. This is not very expected and convenient during development and forces wrapping the handler in custom exception logging handler. 

For example, this script won't print anything : 

```javascript
var raml = require('raml-parser');

process.on('uncaughtException', function(err) {
    console.log('Won\'t catch anything: ' + err);
});

var definition = [
    '#%RAML 0.8',
    '---',
    'title: MyApi',
    'baseUri: http://myapi.com',
    '/Root:'
].join('\n');

raml.load(definition).then(function (data) {
    throw "Did something wrong in handling";
}, function (error) {
    console.log('Error parsing: ' + error);
});
```

Expected behavior: similar to default callback error handling, e.g.

```javascript
setTimeout(function() {
    nonexistentFunc();
}, 500);
``` 
will raise `uncaughtException` event, and if not handled - an error with stacktrace will be printed in the console: 

```bash
$ node lib/err.js

<path>/err.js:33
nonexistentFunc();
^
ReferenceError: nonexistentFunc is not defined
    at Object.<anonymous> (<path>/err.js:33:1)
```

**Comment by dmartinezg** [comment]
Hi @mgurov, that is effectively how [promises work](https://promisesaplus.com/#point-42). When an exception is thrown in a promise body, the whole promise is rejected with the error as argument. Since the exception _is handled_ by the Promise (in this case we are using the [q module](https://www.npmjs.com/package/q), your event for unhandled exception will not get fired.

This is how you should catch errors in your code (I am using your first snippet as base):

```javascript
var raml = require('raml-parser');

var definition = [
    '#%RAML 0.8',
    '---',
    'title: MyApi',
    'baseUri: http://myapi.com',
    '/Root:'
].join('\n');

raml.load(definition).then(function (data) {
    throw "Did something wrong in handling";
})
.catch(function (error) {
    console.log('Error parsing: ' + error);
});
```

I will be closing this issue.

**Comment by mgurov** [comment]
Hi @dmartinezg, 

Thank you for the quick reply. Yes, the `catch` of the q promise worked OK for me, no issue.

I used to have some experience with promises before, via angular.js, but the `catch` there is a shorthand to `promise.then(null, errorCallback)` (see https://docs.angularjs.org/api/ng/service/$q#the-promise-api ). Hence the confusion. Maybe adding a pointer to [q](https://github.com/kriskowal/q#handling-errors) to the top level documentation would save time next time.
