### ISSUE TITLE
Release merges to master on npm, and tag versions properly

### ISSUE THREAD

**Issue by iki** [raml-org/raml-js-parser#125]
Please do release merges on master to npm, and tag versions properly.

Currently [master](https://github.com/raml-org/raml-js-parser/commits/master) is ahead of [released 0.8.9](https://www.npmjs.com/package/raml-parser). That includes an unreleased fix for #122 that is blocking us. Also [tags](https://github.com/raml-org/raml-js-parser/tags) are not set properly.

That said, thanks for a great API documentation tool!

**Comment by dmartinezg** [comment]
Apologies for the delay. 

0.8.10 is released and tagged.

Thanks for your support

**Comment by iki** [comment]
Awesome, thank your for a quick response @dmartinezg!
