### ISSUE TITLE
Can't throw Errors anywhere after promise resolved.

### ISSUE THREAD

**Issue by maxmert** [raml-org/raml-js-parser#139]
```js
raml.load(fileData).then(function(data) {
    ---some code here---
},
function(error) {
   throw new Error('Custom error'); // Doesn't work
});
```

All promises wrapped with try/catch?

**Comment by blakeembrey** [comment]
Hi @maxmert! Yes, you're correct. Promises are wrapped in a try/catch, so to catch any errors thrown in the chain you'll need to chain another error handler (e.g. `p.then(null, function (err) {})` or `p.catch(function (err) {})`). Let me know if this answers your issues :smile:

**Comment by maxmert** [comment]
Thank you for your answer, but still I can not throw there:
```js
raml.load(fileData).then(function(data) {
    ---some code here---
},
function(error) {
   throw new Error('Custom error'); // Doesn't work
}).catch(function(error){
    throw error;  // Doesn't work
});
```

I think I miss something. :)

**Comment by blakeembrey** [comment]
@maxmert It's always wrapped in a `try/catch`. You can't throw inside a promise, it'll just cause an error with the promise that is chained. When you throw, it rejects the promise and you need to chain with `.catch(fn)` or `.then(null, fn)` to receive the error. This exists with promises to avoid the issues associated with `try/catch`, namely that you can't do it with asynchronous code.

**Comment by maxmert** [comment]
Got it. Thank you =)
