### ISSUE TITLE
JSON-lint fails to validate correct unicode encoding

### ISSUE THREAD

**Issue by sbdev** [raml-org/raml-js-parser#151]
JSON-lint doesn't correctly validate unicode format `\uFFFF` and admits only numeric unicode values in their regular expression (i.e. `\u1234`).
https://github.com/codenothing/jsonlint/blob/3b09919cb62d4d46d07fd57bf5730b35c87b3c9c/jsonlint.js#L7

This results in errors in raml-parser if a json schema include unicode encodings such as this:
```
"fieldName":{
   "type":"string",
   "description":"blah blah",
   "maxLength":16,
   "pattern":"^[A-Z\u017D\\u017E]*$"
},
```

This issue has been raised in JSON-lint but no solution has been yet released:
https://github.com/codenothing/jsonlint/issues/2

**Comment by dmartinezg** [comment]
This should be fixed by #157
