### ISSUE TITLE
Parser does validate missing responses

### ISSUE THREAD

**Issue by IvanGoncharov** [raml-org/raml-js-parser#152]
According to RAML spec:
>Responses MUST be a map of one or more HTTP status codes, where each status code itself is a map that describes that status code.

But `raml-parser` validates following constructions:
```yaml
responses: 
    204: 
```

Real life example: https://github.com/raml-apis/GitHub/blob/staging/api.raml#L2121

**Comment by dmartinezg** [comment]
At the same time, RAML was designed so that missing stuff does not punish you, when a value is mandatory, the RAML spec says so, otherwise, a null is allowed.
