### ISSUE TITLE
RAML v1.0

### ISSUE THREAD

**Issue by JaniszM** [raml-org/raml-js-parser#163]
What about support for new RAML 1.0? http://docs.raml.org/specs/1.0/

**Comment by dmartinezg** [comment]
Hi @JaniszM, this parser will be superseded by https://github.com/raml-org/raml-js-parser-2 as soon as it is ready for public usage.

That parser already supports 0.8 and 1.0 versions.

**Comment by JaniszM** [comment]
Great.
