### ISSUE TITLE
object2raml

### ISSUE THREAD

**Issue by JaniszM** [raml-org/raml-js-parser#167]
How can I parse loaded raml file again into raml file?

I did `ramlParser.loadFile(raml).then(function(data){...stuff...}` and I changed raml file and now I want to convert it again into raml. How can I do this ? :)

**Comment by dmartinezg** [comment]
You can use this library:

https://github.com/mulesoft/raml-object-to-raml

It will only serialize, visible data, comments, will get lost, and it will probably export traits and resource types mixed in with the resources.

**Comment by JaniszM** [comment]
Looks like this not working at all. Among all file exported only:

    #%RAML 0.8
    title: changed
    version: 1.0.0
    baseUri: /v1
    schemas: []
:D
