### ISSUE TITLE
Parsing schemas cause replacing reference of schema by schema object

### ISSUE THREAD

**Issue by JaniszM** [raml-org/raml-js-parser#168]
Like in subject, If I have schema in my raml e.g.:
`    -   Error: !include error-schema.json`
and I use it:

            "400": 
                description: Request validation error.
                body: 
                    application/json: 
                        schema: Error
                        example: '{"status":1,"description":"sample description","code":1}'

than raml parser replaces schema reference by putting here (in 'schemas' and all 'schema' tags), whole schema object. In that case schemas become useless because are not being used...

**Comment by dmartinezg** [comment]
Hi @JaniszM, it looks like you want the un-transformed output from the parser, that can be done, simply by asking the parser not to `transform` the input via a feature flag like this:

https://github.com/raml-org/raml-js-parser/blob/master/test/specs/parser.js#L90

Although in that case, the RAML parser is hardly much better than a YAML parser which follows the `!include` tag.

**Comment by plukevdh** [comment]
The Java RAML Parser (v0.8) parses this differently with the result I believe @dmartinezg is desiring. Rather than replacing the schema with the definition import, it leaves the schema name in place. Example RAML:

```raml
schemas:
  - SessionRequest: !include schemas/requests/session.json

/session:
  post:
    description:
      User Login.
    body:
      application/json:
        schema: SessionRequest
        example: !include examples/requests/session.json
```

 From my Intellij debugger, when read via the Java RAML parser, the result looks like the following:

![](http://d.pr/i/12re0/3ePw5xaZ+)

Note the "Schema" field reads "SessionRequest".

However, when this gets parsed by the JS RAML parser, the following is output (truncated for brevity):

```json
    {
      "relativeUri": "/session",
      "methods": [
        {
          "description": "User Login.",
          "body": {
            "application/x-www-form-urlencoded": {
              "formParameters": {
                "email": {
                  "description": "Email Address.",
                  "type": "string",
                  "displayName": "email"
                },
                "password": {
                  "description": "Password.",
                  "type": "string",
                  "displayName": "password"
                }
              }
            },
            "application/json": {
              "schema": "{\n  \"title\": \"Session Request Schema\",\n  \"type\": \"object\",\n  \"properties\": {\n    \"email\": {\n      \"type\": \"string\"\n    },\n    \"password\": {\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\"email\", \"password\"]\n}\n",
              "example": "{\n  \"email\": \"test@articulate.com\",\n  \"password\": \"test1234\"\n}\n"
            }
          },
          "protocols": [
            "HTTPS"
          ],
          "method": "post"
        }
      ],
      "relativeUriPathSegments": [
        "session"
      ]
    },
```

In this case, the schema is dropped in place of the Schema used. In my case this a) duplicates data b) makes it harder to understand which previously defined schema is being referred to.

**Comment by plukevdh** [comment]
For reference on how the two parsers differ from a test perspective: 

https://github.com/raml-org/raml-java-parser/blob/master/src/test/java/org/raml/parser/builder/SchemaBuilderTestCase.java#L73-L74 

vs.

https://github.com/raml-org/raml-js-parser/blob/master/test/specs/parser.js#L5723-L5762

**Comment by plukevdh** [comment]
And really, to fix, all you have to *not* do is this: https://github.com/raml-org/raml-js-parser/blob/c8edf033a40c33a28161fa67a57fd710e7ddb005/src/composer.coffee#L61

**Comment by dmartinezg** [comment]
Hi @plukevdh, you are right that is where we are transforming the output. 

As I mentioned above, the way to avoid this transformation is by calling the parser _with_ the flag `transform` to off.

```javascript
raml.load(definition, 'filename.yml', {transform: false})
  .then(function(output){
    //do something with output here
  });

```

**Comment by JaniszM** [comment]
Sorry for late answer, I was on vacation :)
@plukevdh you got it well I think.
@dmartinezg I checked flag `{transform: false}`. Looks this is exactly what I need :) Thanks.

**Comment by JaniszM** [comment]
Ok, after checking it again I got serious problem. disabling transform makes whole structure of object like this visible in raml file. This mean that raml-object-to-raml lib cannot parse it anymore :( Is it possible any other way to use schemas like in transform disabled mode but still keep the structure of trasformed object?

**Comment by plukevdh** [comment]
Going to check out `{transform: false}` to see if it works for my case as well.

**Comment by plukevdh** [comment]
This does not follow the Java parser convention either as it doesn't perform _any_ of the transformations. It doesn't collect the endpoints (`/session`) under the `endpoints` property. This seems like a very unfortunate divergence of the two parsers.

**Comment by plukevdh** [comment]
@dmartinezg any comment on what we might do to make the two parsers work more similarly?

**Comment by dmartinezg** [comment]
Hi @plukevdh and @JaniszM, I just pushed a branch, adding a specific flag for this, you can check https://github.com/raml-org/raml-js-parser/commit/4d49f906c7c3ad8dc302e8bea559c4dbfce4225c#diff-51b64dc80fa386af7ffcd496680224fdR124 to see how to disable the behaviour.

would this be enough for you?

**Comment by plukevdh** [comment]
Looks legit, I need to test though.

**Comment by dmartinezg** [comment]
I just pushed 0.8.15 to npmjs, it should make testing easier.

**Comment by plukevdh** [comment]
:+1: works as required. thanks for this solution. I'd be curious if it solves @JaniszM's problem as well.

**Comment by JaniszM** [comment]
Works perfectly :)
